### PR TITLE
Custom Error Page in UI

### PR DESCRIPTION
**Pull request by MatteoGheza**
**EDIT: view the last comment, now the custom error page is in the server code and works in the browser, without Electron.**

I was working on a custom error page for replacing the simple "dialog" in Electron code.

Screenshot and video recording of the error page.
0phheB2p5D

https://user-images.githubusercontent.com/27729549/128645058-d64bd35d-c7df-4fdb-8ccc-e2b7cfaec9a9.mp4

_(for the last video I added a simple "test();" to server-side socket.io listener for the login)_

Pressing the "Open a bug report on Github" button, the webpage comunicates with main.js with IPC that opens TallyArbiter new issue page on Github in browser.
The link contains some parameters, so the new issue is pre-filled with version and logs.
Excerpt from the code ```let url = `https://github.com/josephdadams/TallyArbiter/issues/new?labels=bug&template=bug.yaml&title=%5BBug%5D%3A+&version=${app.getVersion()}&logs=${encodeURIComponent(logs)}`;```

### CODE REVIEW

**Comment by hrueger** [comment]
Pretty cool 😃👍👍👍 I think I know where you got the look from ;-)

Just as a litte finish, we could give the scrollbars a more flat apperance: http://webkit-scroll-gen.sourceforge.net/

This could be something for the main UI, too

**Comment by hrueger** [comment]
And what about masking the security and Cloud section in the config file? People could easily leak sensitive information otherwise...

**Comment by JTF4** [comment]
Only thing I would do is trim the security part from the config file. Since we just implemented security features like brute force protection it makes no sense for them to upload their username and password with the config. Especially if it's cloud hosted.

**Comment by josephdadams** [comment]
Love this. Could also be great to trap process errors on the server side and offer a similar link via modal pop up if the user is not using electron to view TA but is viewing just in the browser.

Also wondering if we could auto submit an error report asynchronously somehow and store that in a file somewhere and if we see an error occur often, it would be something to act on.

**Comment by josephdadams** [comment]
I’m talking about this area:
https://github.com/josephdadams/TallyArbiter/blob/2bca96d041c7a9802029ffe26627d779eba0b83d/index.js#L760

Obviously a new PR, just referencing it here for conversation.

**Review by JTF4 — COMMENTED** [review]
I like it! All the code looks good. 

The only thing I would possibly change in the future is making the error page look more like tally arbiter and less like a BSOD, but I'm nit picking at that point.

All in all it's a super cool addition and it give the user much more data to easily open a bug request with.

**Comment by JTF4** [comment]
Oh. One other thing. Let's make a config upload section for the bug request form. That way we can get everything at once.

**Comment by MatteoGheza** [comment]
> Oh. One other thing. Let's make a config upload section for the bug request form. That way we can get everything at once.

Done. I updated _bug.yaml_ and I added support for new fields in main.js.
New url: ````https://github.com/josephdadams/TallyArbiter/issues/new?labels=bug&template=bug.yaml&title=%5BBug%5D%3A+&version=${app.getVersion()}&config=${encodeURIComponent(config)}&logs=${encodeURIComponent(logs)}&stacktrace=${encodeURIComponent(err.stack)}````

**Comment by josephdadams** [comment]
@MatteoGheza feel free to merge this when you are ready

**Comment by MatteoGheza** [comment]
Fixed it for #162
Now it works without Electron.
Now the error page is just an Angular component in the UI, and errors are now reported by the server, and not by Electron.
New features/improvements:
- Everything in the UI as a component
- Unexpected errors are now saved in a file in the directory `ErrorReports` as json files with the following schema:
`{
    datetime: Date;
    stacktrace: string;
    logs: string;
    config: object;
}` (BTW the _id_ of the error report is just the filename, generated with uuidv4)
- When an unexpected error is detected, the server emits a websocket event (`server_error`)

**Comment by MatteoGheza** [comment]
Thanks to CodeQL, I noticed that the last commit introduces an "high severity security vulnerability", since everything passed to socket event `get_error_report` is passed to `getErrorReport`, opened and parsed as JSON.
This leads to Remote File Inclusion (RFI) attacks and to DoS attacks.
I'm fixing it right now.

**Comment by MatteoGheza** [comment]
Sorry, I forgot to add credits to the original Codepen.
Added in the last commit.

**Comment by josephdadams** [comment]
Really slick. Great work!

**Comment by JTF4** [comment]
The codeQL thing is pretty cool! I would have never thought about that vulnerability.

**Comment by josephdadams** [comment]
@JTF4 I don’t think the error reporting page design needs to be changed at the moment. Hopefully, it will get very little views 😃 because our code is so awesome. And it can always be changed later.

**Comment by JTF4** [comment]
Oh! I meant that as a "I would love to do this in the future" thing. I'm just fine with the current design.

**Comment by MatteoGheza** [comment]
Only one feature remains: _Send "server_error" event again if there weren't clients during the error_

**Comment by josephdadams** [comment]
How about a master Boolean and an interval; if the user answers the error modal it clears the Boolean and the interval, otherwise it pops up again

**Comment by MatteoGheza** [comment]
I read your comment only now. Good idea.
Now I implemented a simple "readed error reports list", so when someone opens the setting page and there are unreaded reports, a popup is shown.

**Comment by MatteoGheza** [comment]
Done! No more TODOs for now!🎉
Waiting for reviews.

**Review by josephdadams — APPROVED** [review]
I approve :)

**Comment by MatteoGheza** [comment]
Closes #162

**Pull request merged**
