### PR TITLE
Move listener clients to this repo

### PR DESCRIPTION
**Pull request by MatteoGheza**
I was trying to update clients for the new server version, and I found it a bit difficult for a beginner (find link to GitHub device page in documentation, fork the repo, update it and open a PR in a repo that can be forgotten by maintainers).
So, I did what hrueger asked in #214 and I started moving every device firmware code to this repo, in the directory listener_clients.

Doing this, I think that opening issues regarding clients, contributing to firmwares and updating them when we update TallyArbiter server code can be easier, even for a beginner.

I tried to migrate original commits, to keep authors and history (I replaced some... useless test values in some of you commits @josephdadams), using `git format-patch`, replacing some values and using `git am` for "importing" them into this repo.

Currently, there are some TODOs:
- [x] Check if there are open PR in devices repos
- [x] Update firmwares for v3.0.0 server
- [x] Add support for MDNS discovery and add captive portal for WiFi connection
- [x] Detect server version
- [x] Import clients from other repos
- [x] Configure CI to compile firmwares at every release

Tested clients:
- [x] M5Atom
- [x] TTGO_T
- [x] blink1
- [x] ESP32 with Adafruit NeoPixel
- [x] gpo
- [x] M5Stick(c)
- [x] Pimoroni Blinkt
- [x] relay

### CODE REVIEW

**Comment by josephdadams** [comment]
Great job!

**Comment by MatteoGheza** [comment]
I tried to update the logic.
@mg-1999 can you test the last commit?
BTW now I have a TTGO-T to test the firmware, _but Windows won't let me delete an arduino library from the folder, reporting "access denied" even though I'm using powershell as administrator and if "Administrator" should have write rights to the file..._ so i can't compile Arduino firmwares on my setup.
I have to re-install the Arduino IDE and everything...

**Comment by mg-1999** [comment]
Last commit works as expected! Thanks for fixing it.

Now onto the next one 🚀  M5StickC?

**Comment by MatteoGheza** [comment]
> Last commit works as expected! Thanks for fixing it.
> 
> Now onto the next one 🚀 M5StickC?

Yes! Thanks!
I'm working on TTGO, and now it's working quite well.

**Comment by MatteoGheza** [comment]
Tested everything except M5Stick(c)

**Comment by mg-1999** [comment]
m5Stick C has the same problem as the m5atom. The tally state is stuck after there are no tally updates for the device.

**Comment by MatteoGheza** [comment]
Fixed.

**Comment by MatteoGheza** [comment]
Done. CI is working and every listener client supports v3.0.0.
@mg-1999 can you test M5Stickc?

**Comment by josephdadams** [comment]
@MatteoGheza let's be sure to update all the readme.md files for each client as well as the official documentation on how to load the clients, if we are shipping the .hex files

**Comment by josephdadams** [comment]
https://github.com/josephdadams/TallyArbiter/blob/fb3085ca156c72eacd58eb4b9560b3477765a0b7/listener_clients/gpo-listener/gpo-listener.py#L73

Should this be port `4455`?

**Comment by mg-1999** [comment]
Yes the m5stickC was indeed fixed, but don't have the Cplus to test. But don't think it will be a major problem

**Comment by MatteoGheza** [comment]
@josephdadams @mg-1999 what do you think about this README?
Please note that the "1. Using a pre-builded version" section is going to change ASAP.

**Comment by MatteoGheza** [comment]
Merging this so I can start working on #270
I'll open a new issue for the updating the documentation

**Comment by hrueger** [comment]
Sounds great.

I just saw https://github.com/electron/electron/issues/14545 . But as a workaround until that issue is fixed, we can detect if we're in the electron window and then open a Chrome window.

**Pull request merged**
