### PR TITLE
Change bonjour to ciao

### PR DESCRIPTION
**Pull request by jamessandison**
Bonjour hasn't been updated for 7 years, and I had some problems getting the server IP address from it. Bonjour-HAP has since replaced it, and now Ciao has replaced Bonjour-HAP.

Upon changing the library, I have been able to find the tally arbiter server on the network via Bonjour/mDNS. (note: it didn't work on my desktop computer [I think firewall issues], but worked fine on my raspberry pi)

https://github.com/homebridge/ciao

### CODE REVIEW

**Comment by mg-1999** [comment]
Ciao only publishes the TA server on the network, but has no support for finding devices like the atem. 

[Bonjour-service](https://github.com/onlxltd/bonjour-service) does support for scanning the network and looks like a more direct replacement

**Comment by jamessandison** [comment]
I might have missed it being used elsewhere sorry! I'm not currently aware of it being used for discovery of other devices? I'm not sure if this is a planned feature? This is my first open source contribution (albeit very small), so I might not have looked into it properly, but when I did a search in the code for bonjour, it only appeared in the index.ts for the socketio server and a listener client.

**Comment by josephdadams** [comment]
I'm not sure how implemented it is but yes it is a planned feature to detect other things, definitely for ATEM, and for other source types as we are able to implement. Would love to have scanning of listener clients as well to just try to auto detect as many things as possible. Would be great for device actions also - want to have TA press a Companion button - here's a list of all the detected Companion instances on the network etc.

**Comment by jamessandison** [comment]
I'll try and change it to bonjour-service tomorrow and see how I go :)

**Comment by hrueger** [comment]
As far as I know, @MatteoGheza implemented the ATEM discovery in #302. However, this PR was merged into the `improve-logins` branch and not into the master branch, I don't know why. That PR #247 is still open.

Maybe you can team up with @MatteoGheza to avoid creating conflicts?

**Comment by jamessandison** [comment]
I saw @MatteoGheza's pull request, but I'm not too sure how to commit to it (sorry bit of a git noob)

**Comment by MatteoGheza** [comment]
> I saw @MatteoGheza's pull request, but I'm not too sure how to commit to it (sorry bit of a git noob)

I'm sorry, I committed it to the wrong branch.
I'm fixing this today.

**Comment by mg-1999** [comment]
> > I saw @MatteoGheza's pull request, but I'm not too sure how to commit to it (sorry bit of a git noob)
> 
> I'm sorry, I committed it to the wrong branch. I'm fixing this today.

You don't have to, improved logins with the atem discovery is already merged into main

**Comment by MatteoGheza** [comment]
> > > I saw @MatteoGheza's pull request, but I'm not too sure how to commit to it (sorry bit of a git noob)
> > 
> > I'm sorry, I committed it to the wrong branch. I'm fixing this today.
> 
> You don't have to, improved logins with the atem discovery is already merged into main

No, I don't think. I'll merge this in the next hours, because I have to fix merge conflicts.

**Comment by MatteoGheza** [comment]
I merger improve_logins.
What do you think about using bonjour-service @jamessandison ?

**Comment by jamessandison** [comment]
@MatteoGheza I tried using bonjour-service but I was having issues - It also seems like after the improve-logins merge, I can't login with admin/12345, even with a fresh configuration file.

**Comment by MatteoGheza** [comment]
> @MatteoGheza I tried using bonjour-service but I was having issues - It also seems like after the improve-logins merge, I can't login with admin/12345, even with a fresh configuration file.

I'm really sorry about that.
Can you please open a new issue for reporting the bug? Can you attach the log file?

BTW have you already run `npm i`?

**Comment by jamessandison** [comment]
I've had a bit of a chance to work on it again, and bonjour-service still appeared as 0.0.0.0 on my esp32 scanner, but would not appear on a bonjour browser on my phone, and on my desktop computer, would not have an ip address.

I changed the broadcast of the device to ciao, and i have currently left it as bonjour-service in my tests, but I don't have any blackmagic hardware at home, so I will have to go to church and test it - will keep you guys updated :)

**Comment by JTF4** [comment]
@jamessandison any update on this?

**Comment by hrueger** [comment]
@jamessandison Can you push the changes in case someone wants to continue working on it? That would be great.

**Comment by hrueger** [comment]
superseded by #437

**Pull request closed without merging**
