### PR TITLE
v3.0.5

### PR DESCRIPTION
**Pull request by Jocke4f**
Input to release info, should cover step (1) in Maintainers list.

Updated list of contributors in package.json based on pull requests since v3.0.4 so anyone involved in code reviews have been missed.

Features:
(relay-listener) Added support for multiple relay boards
(OBS) Added support for OBS 28 (websocket protocol version 5) and preview/program tally for OBS 28
(ui) Added use of device name instead of client only on chat
(ui) Added enable/disable chat options to tally view
(m5AtomMatrix) Added support for password

Fixes:
(build) Updated build environments.
(build) Updated external dependencies.
(gpo-listener) Correction of connection handling and device reassignment
(m5AtomMatrix-listener) Corrected displayed camera number
(m5StickC-listener) Correction to setup the TallyArbiter IP address in the UI and internal LED definition
(relay-listener) Improved error handling
(ui) Improved server reconnection and connection lost status
(Analog Way Livecore)  Added connect()/reconnect() to enable reconnect handling.
(ATEM) Improved Atem source handling
(Blackmagic VideoHub) Removed premature connected status.
(Newtek Tricaster) Added connect()/reconnect() to enable reconnect handling.
(OBS) Removed bug causing infinite reconnect attempts
(Roland VR) Added connect()/reconnect() to enable reconnect handling.
(vMix) Added connect()/reconnect() to enable reconnect handling. Fix for #532. Removed memory leak at connect handling

### CODE REVIEW

**Comment by JTF4** [comment]
Please elaborate a little more on what you're asking for with your PR. 

Are you looking to have a new pre-release version pushed out?

**Comment by Jocke4f** [comment]
Sure no problem. Yes, I'm asking for a pre-release version to be pushed out. There are several connect/reconnect issues we would like to have available in a release for a more controlled deployment in our environement and also make them easier available for others

I raised the need for an additional pre-release on 3.0.x with Joseph and he suggest a PR as way forward.

I don't have a complete overview of all bug fixes implemented. By browsing the open issues does it look that some open issues possibly is solved in a new pre-release such as #603, #463 and #464.

**Comment by josephdadams** [comment]
I'm only seeing that you updated `package.json` in your commit? Where's the rest of the code changes?

**Comment by Jocke4f** [comment]
I realize that I was unclear. There are several code changes that I submitted during the summer that already are on the Master branch that I would like to have in a pre-release.. I don't have any additional code changes up my sleeve right now.

**Comment by josephdadams** [comment]
Take a look at the build actions that are failing. It looks like some dependencies will need to be upgraded.

**Comment by josephdadams** [comment]
I just gave you rights to the repo, @Jocke4f, to save us all some time

**Comment by Jocke4f** [comment]
I will take a look at them. To my knowledge are they not new failings based on comparison with other recent builds.

**Pull request merged**
