### PR TITLE
external Address option

### PR DESCRIPTION
**Pull request by videojedi**
Add a new value to config file. Will display in home page as a QR code and extra link.

example
 "externalAddress":"http://0.0.0.0:4455/#/tally"

### CODE REVIEW

**Comment by hrueger** [comment]
@MatteoGheza
> Now we need to implement an input or a modal for replacing the external address and a new websocket event for applying changes to it in the config.

What about a global "Settings" page where users can also change other config settings like passwords? I'd also really like to see a users system for multiple users with different login credentials.

**Review by MatteoGheza — APPROVED** [review]

**Comment by MatteoGheza** [comment]
I think we can merge this, so @videojedi can start using this as an "hidden feature" until we implement a "global settings" page.

**Comment by hrueger** [comment]
Maybe someone can delete the `.code-workspace` file? For me it appears to still be there

**Comment by MatteoGheza** [comment]
> Maybe someone can delete the `.code-workspace` file? For me it appears to still be there

I'll do it in master

**Comment by MatteoGheza** [comment]
Done

**Pull request merged**
