### PR TITLE
Code clean up in m5stickc-listener

### PR DESCRIPTION
**Pull request by Jocke4f**
Changes in **m5stickc-listener.ino**
- Removed redefined defines that are not used.
- Changed `GetVbatData` to `GetBatVoltage` due to deprecation in M5StickCPlus\src\AXP192.h.
- Cleaned up faulty log printouts.
- Added load of Settings screen when network connection is successful.
- Added printout when configuration times out due to inactivity.

Changes in **README.md**
- Updated the readme file to be in line with the code.

Future enhancements could be:
- Change to proper MAC address in the device name. This is also used in the name of the temporary AP for initial configuration.
- Add more descriptive information at first startup regarding configuration.

### CODE REVIEW

**Review by MatteoGheza — APPROVED** [review]

**Comment by josephdadams** [comment]
Thanks for all this, @Jocke4f !

**Comment by Jocke4f** [comment]
In the 2nd commit the following enhancements have been included:

- Parts of the MAC address is now used for the `SSID` for the configuration, in WiFi `hostname` and also as `type`/name in Tally Arbiter.
- More descriptive text during first time start, i.e., no networking configurations exist.

**Comment by josephdadams** [comment]
This is great!

**Comment by josephdadams** [comment]
Is this ready to merge?

**Comment by Jocke4f** [comment]
This PR is now ready to be merged.

Is it not taking into consideration the changes that are planned in https://github.com/josephdadams/TallyArbiter/pull/358. Such considerations/adaptations are part of work for that PR when trying to unify the code base.

**Pull request merged**
