### PR TITLE
Added CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Jassi10000**
Added CODE_OF_CONDUCT.md to the repo

@MatteoGheza @JTF4 
Sir can you please review and merge this

### CODE REVIEW

**Comment by Jassi10000** [comment]
@hrueger  and @josephdadams Please review the latest changes

**Comment by hrueger** [comment]
@Jassi10000 thanks for the update. However, as the files are now deleted, when we merge the PR, we lose those files in the main branch, too...
So it would be great if you could just copy those files from the main branch here and commit that. Then, this PR should only show "1 file changed"

**Comment by hrueger** [comment]
@MatteoGheza I'd prefer the "squash and merge" strategy for this PR, because then all the commit are squashed into a single one and we don't have the removal and adding back of the `package.json` files in our history.

**Comment by Jassi10000** [comment]
Should I close this and make another PR ? @hruger

**Comment by hrueger** [comment]
If you want, you can, but it should also work if you just add back the files.

If we merge using the squash method, only a single commit will appear in the history.

**Comment by JTF4** [comment]
Closing due to #261

**Pull request closed without merging**
