### PR TITLE
Add sentry.io error logging

### PR DESCRIPTION
**Pull request by JTF4**
Sentry.io captures and logs errors in the cloud so that we know what the biggest issues are in TA

### CODE REVIEW

**Comment by JTF4** [comment]
@josephdadams thoughts on this PR?

**Comment by josephdadams** [comment]
I’m good with it as long as it’s opt in not opt out. Turned off by default.

**Comment by JTF4** [comment]
Users are now opted out be default

**Comment by JTF4** [comment]
@MatteoGheza it works great!

**Pull request merged**
