### PR TITLE
M5Stick Atom - Reset WiFi credentials when button pressed by 5 seconds

### PR DESCRIPTION
**Pull request by Everton747**
M5Stick Atom - Reset WiFi credentials when button pressed by 5 seconds

### CODE REVIEW

**Comment by josephdadams** [comment]
Looks great, @Everton747! I'll merge it if you add a commit to update the readme file about this feature.

**Comment by josephdadams** [comment]
@MatteoGheza is this needed with your new client platform?

**Comment by MatteoGheza** [comment]
> @MatteoGheza is this needed with your new client platform?

In the new client platform, it should work.

**Comment by Everton747** [comment]
Readme updated!

**Pull request merged**
