### PR TITLE
Truncate logs and bug title

### LINKED ISSUE #187: [Bug]: Bug Report does not work
### What happened?

I tried to create a bug report using the great new BSOD screen, and got this page (by GitHub):
grafik

this was the generated request URL:
```
https://github.com/josephdadams/TallyArbiter/issues/new?labels=bug&template=bug.yaml&title=%5BBug%5D%20TypeError%3A%20Cannot%20set%20property%20%27label%27%20of%20undefined&version=2.0.13&config=%7B%0A%20%20%22security%22%3A%20%7B%0A%20%20%20%20%22username_settings%22%3A%20%22admin%22%2C%0A%20%20%20%20%22password_settings%22%3A%20%2212345%22%2C%0A%20%20%20%20%22username_producer%22%3A%20%22producer%22%2C%0A%20%20%20%20%22password_producer%22%3A%20%2212345%22%0A%20%20%7D%2C%0A%20%20%22sources%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22data%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22port%22%3A%204000%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22TestSource%22%2C%0A%20%20%20%20%20%20%22sourceTypeId%22%3A%20%2205d6bce1%22%2C%0A%20%20%20%20%20%20%22reconnect%22%3A%20true%2C%0A%20%20%20%20%20%20%22enabled%22%3A%20true%2C%0A%20%20%20%20%20%20%22id%22%3A%20%22c580b234%22%2C%0A%20%20%20%20%20%20%22connected%22%3A%20true%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22data%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22ip%22%3A%20%22127.0.0.1%22%2C%0A%20%20%20%20%20%20%20%20%22port%22%3A%204444%2C%0A%20%20%20%20%20%20%20%20%22password%22%3A%20%22password%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22OBS%22%2C%0A%20%20%20%20%20%20%22sourceTypeId%22%3A%20%224eb73542%22%2C%0A%20%20%20%20%20%20%22reconnect%22%3A%20true%2C%0A%20%20%20%20%20%20%22enabled%22%3A%20true%2C%0A%20%20%20%20%20%20%22id%22%3A%20%227ec865f7%22%2C%0A%20%20%20%20%20%20%22connected%22%3A%20true%0A%20%20%20%20%7D%0A%20%20%5D%2C%0A%20%20%22devices%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22name%22%3A%20%22A%22%2C%0A%20%20%20%20%20%20%22enabled%22%3A%20true%2C%0A%20%20%20%20%20%20%22id%22%3A%20%22c5f78303%22%2C%0A%20%20%20%20%20%20%22linkedProgram%22%3A%20false%2C%0A%20%20%20%20%20%20%22linkedPreview%22%3A%20false%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22name%22%3A%20%22B%22%2C%0A%20%20%20%20%20%20%22enabled%22%3A%20true%2C%0A%20%20%20%20%20%20%22id%22%3A%20%2227a27d99%22%2C%0A%20%20%20%20%20%20%22linkedProgram%22%3A%20false%2C%0A%20%20%20%20%20%20%22linkedPreview%22%3A%20false%0A%20%20%20%20%7D%0A%20%20%5D%2C%0A%20%20%22device_sources%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22deviceId%22%3A%20%22c5f78303%22%2C%0A%20%20%20%20%20%20%22sourceIdx%22%3A%20%221%22%2C%0A%20%20%20%20%20%20%22rename%22%3A%20true%2C%0A%20%20%20%20%20%20%22address%22%3A%20%22Szene%22%2C%0A%20%20%20%20%20%20%22sourceId%22%3A%20%227ec865f7%22%2C%0A%20%20%20%20%20%20%22id%22%3A%20%2206aa7229%22%0A%20%20%20%20%7D%0A%20%20%5D%2C%0A%20%20%22device_actions%22%3A%20%5B%5D%2C%0A%20%20%22tsl_clients%22%3A%20%5B%5D%2C%0A%20%20%22tsl_clients_1secupdate%22%3A%20false%2C%0A%20%20%22cloud_destinations%22%3A%20%5B%5D%2C%0A%20%20%22cloud_keys%22%3A%20%5B%5D%2C%0A%20%20%22bus_options%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%22e393251c%22%2C%0A%20%20%20%20%20%20%22label%22%3A%20%22Preview%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22preview%22%2C%0A%20%20%20%20%20%20%22color%22%3A%20%22%233fe481%22%2C%0A%20%20%20%20%20%20%22priority%22%3A%2050%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%22334e4eda%22%2C%0A%20%20%20%20%20%20%22label%22%3A%20%22Program%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22program%22%2C%0A%20%20%20%20%20%20%22color%22%3A%20%22%23e43f5a%22%2C%0A%20%20%20%20%20%20%22priority%22%3A%20200%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%2212c8d698%22%2C%0A%20%20%20%20%20%20%22label%22%3A%20%22Preview%20%2B%20Program%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22previewprogram%22%2C%0A%20%20%20%20%20%20%22color%22%3A%20%22%23ffc107%22%2C%0A%20%20%20%20%20%20%22priority%22%3A%20201%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%2212c8d699%22%2C%0A%20%20%20%20%20%20%22label%22%3A%20%22Aux%201%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22aux%22%2C%0A%20%20%20%20%20%20%22color%22%3A%20%22%230000FF%22%2C%0A%20%20%20%20%20%20%22priority%22%3A%20100%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%2212c8d689%22%2C%0A%20%20%20%20%20%20%22label%22%3A%20%22Aux%202%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22aux%22%2C%0A%20%20%20%20%20%20%22color%22%3A%20%22%230000FF%22%2C%0A%20%20%20%20%20%20%22priority%22%3A%20100%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D&logs=%5B29.8.2021%2C%2017%3A58%3A39%5D%20Loading%20the%20stored%20Tally%20Arbiter%20configuration%20file.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Bus%20Options%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%205%20Busses%20configured.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Sources%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%202%20Sources%20configured.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Devices%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%202%20Devices%20configured.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Device%20Sources%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Device%20Actions%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20TSL%20Clients%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20TSL%20Clients%201%20Second%20Updates%20are%20turned%20off.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Cloud%20Destinations%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20Cloud%20Keys%20loaded.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Initiating%20Setup%20for%20Source%3A%20TestSource.%20Type%3A%20Open%20Sound%20Control%20(OSC)%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Source%3A%20TestSource%20%20Creating%20new%20OSC%20connection.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Initiating%20Setup%20for%20Source%3A%20OBS.%20Type%3A%20OBS%20Studio%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Source%3A%20OBS%20%20Creating%20OBS%20Websocket%20connection.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Source%20Setup%20Complete.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Initializing%20Device%20States.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Device%20States%20Initialized.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Setting%20up%20the%20REST%20API.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20REST%20API%20Setup%20Complete.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Starting%20socket.IO%20Setup.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Socket.IO%20Setup%20Complete.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Starting%20OSC%20Setup.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Starting%20VMix%20Emulation%20Service.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Starting%20HTTP%20Server.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Source%3A%20TestSource%20%20OSC%20port%204000%20ready.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20OSC%20Sending%20Port%20Ready.%20Broadcasting%20on%20Port%3A%205958%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Finished%20VMix%20Emulation%20Setup.%20Listening%20for%20VMix%20Tally%20Connections%20on%20TCP%20Port%208099.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Tally%20Arbiter%20running%20on%20port%204455%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Source%3A%20OBS%20%20OBS%20Connection%20opened.%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20OBS%20Tally%20Source%3A%207ec865f7%20Added%20new%20source%3A%20%7B%7BSTREAMING%7D%7D%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20OBS%20Tally%20Source%3A%207ec865f7%20Added%20new%20source%3A%20%7B%7BRECORDING%7D%7D%0A%5B29.8.2021%2C%2017%3A58%3A39%5D%20Source%3A%20OBS%20%20OBS%20Authenticated.%0A%5B29.8.2021%2C%2017%3A59%3A01%5D%20Config%20file%20saved%20to%20disk.%0A%5B29.8.2021%2C%2017%3A59%3A02%5D%20Config%20file%20saved%20to%20disk.%0A%5B29.8.2021%2C%2017%3A59%3A21%5D%20Source%3A%20OBS%20%20Source%20renamed%0A%5B29.8.2021%2C%2017%3A59%3A21%5D%20Caught%20exception%3A%20TypeError%3A%20Cannot%20set%20property%20%27label%27%20of%20undefined%0A&stacktrace=TypeError%3A%20Cannot%20set%20property%20%27label%27%20of%20undefined%0A%20%20%20%20at%20renameOBSSource%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cindex.js%3A3409%3A38)%0A%20%20%20%20at%20OBSWebSocket.%3Canonymous%3E%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cindex.js%3A3331%3A25)%0A%20%20%20%20at%20OBSWebSocket.emit%20(events.js%3A375%3A28)%0A%20%20%20%20at%20OBSWebSocket.Socket.emit%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cnode_modules%5Cobs-websocket-js%5Clib%5CSocket.js%3A18%3A20)%0A%20%20%20%20at%20WebSocket._socket.onmessage%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cnode_modules%5Cobs-websocket-js%5Clib%5CSocket.js%3A121%3A16)%0A%20%20%20%20at%20WebSocket.onMessage%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cnode_modules%5Cws%5Clib%5Cevent-target.js%3A132%3A16)%0A%20%20%20%20at%20WebSocket.emit%20(events.js%3A375%3A28)%0A%20%20%20%20at%20Receiver.receiverOnMessage%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cnode_modules%5Cws%5Clib%5Cwebsocket.js%3A835%3A20)%0A%20%20%20%20at%20Receiver.emit%20(events.js%3A375%3A28)%0A%20%20%20%20at%20Receiver.dataMessage%20(C%3A%5CUsers%5CHannes%5CDesktop%5CAngular%5CTallyArbiter%5Cnode_modules%5Cws%5Clib%5Creceiver.js%3A437%3A14)
```

### Version

latest

### Distribution

Source

### OS

Windows

### What browsers are you seeing the problem on?

Firefox

### If applicable, What Listener Clients are You Using?

_No response_

### TallyArbiter configuration

```javascript
-
```

### Relevant log output

```shell
-
```

### Error stacktrace (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by MatteoGheza**
Closes #187
Note: I haven't tried this code. I don't know if it works. ASAP I'll try it.

### CODE REVIEW

**Comment by MatteoGheza** [comment]
TODO:
- [ ] Try this
- [ ] Truncate config

**Comment by josephdadams** [comment]
Possible to store the error report URL’s github repo path as a variable in case someone forks TA? I don’t want their bug reports coming to us. Of course my hope is that anyone who forks TA does so in order to contribute to the main project.

**Comment by MatteoGheza** [comment]
Done.

**Comment by josephdadams** [comment]
Fine with me to merge, whenever you guys are ready

**Pull request merged**
