### PR TITLE
add support for outgoing TSL UMD 5

### PR DESCRIPTION
**Pull request by NoahCallaway**
Adds support for outgoing TSL UMD v5 Tallies.
Attempts to include most of the features of the v5 protocol.

### CODE REVIEW

**Comment by josephdadams** [comment]
What would it take to add TCP support?

**Comment by NoahCallaway** [comment]
I can probably add it. I'm just not sure I can test it properly.

**Comment by josephdadams** [comment]
That’s what Github Issues are for. We have a great error reporting system. 😃

**Review by MatteoGheza — APPROVED** [review]

**Comment by NoahCallaway** [comment]
Added. 🙂

**Review by MatteoGheza — APPROVED** [review]

**Comment by MatteoGheza** [comment]
This looks great to me.
If anyone agrees, I'll merge this PR today.

**Comment by josephdadams** [comment]
I noticed you changed the StopTSLServer function where it used to say “TSL 3.1 Server stopped” to say TSL 5. This should be reverted.

**Comment by NoahCallaway** [comment]
Whoops!!! My bad.
Great spot. Fixed now.

**Comment by josephdadams** [comment]
Can you update the documentation also? There’s a page that lists what outgoing actions are available.

**Comment by NoahCallaway** [comment]
Done! I think that's the right place.

**Comment by josephdadams** [comment]
@MatteoGheza ready to merge

**Pull request merged**
