### PR TITLE
Add Ember+ support as an outgoing action

### PR DESCRIPTION
**Pull request by netdude78**
I tested this against a Lawo console running 6.4.0.19 and one running 10.8.0.1.  

The ember path needs to be collected & verified using something like Ember+ viewer (available freely online).

Action uses a static dictionary of connections to reuse existing ember+ connections.  Connecting initially to Ember+ can result in a delay that is not great for AfV operations based on tally.

### CODE REVIEW

**Comment by josephdadams** [comment]
@netdude78 can you update the docs too?

**Comment by netdude78** [comment]
Sure. After dinner. I’ll update.

**Comment by josephdadams** [comment]
Thanks!

**Comment by netdude78** [comment]
I added the doc information about Ember+

**Pull request merged**
