### PR TITLE
Recoded the Process Tally function to remove strobing

### PR DESCRIPTION
**Pull request by JTF4**

### CODE REVIEW

**Review by MatteoGheza — APPROVED** [review]

**Comment by josephdadams** [comment]
I'm not in a place to test but if it works, I approve

**Review by josephdadams — APPROVED** [review]

**Comment by MatteoGheza** [comment]
@JTF4 can you apply similar changes to Blink1 listener, Blinkt listener and GPO listener?

**Comment by JTF4** [comment]
Yes. I probably won't be able to get to them today, but I can get them either early next week or tomorrow.

**Comment by josephdadams** [comment]
@JTF4 can you raise an issue about it so we don't forget?

**Pull request merged**
