### PR TITLE
Support for rate limiter and brute force protection

### PR DESCRIPTION
**Pull request by MatteoGheza**
Currently, logins are vulnerable to brute force, since there are no rate limits to the login event in websocket.
I tried implementing rate limits using an advaced library, [rate-limiter-flexible](https://github.com/animir/node-rate-limiter-flexible), so, in the future, we can implement rate limits to the entire application using a custom Express middleware (for example [https://github.com/animir/node-rate-limiter-flexible/wiki/Express-Middleware](https://github.com/animir/node-rate-limiter-flexible/wiki/Express-Middleware)) and/or Websocket connections (https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#websocket-single-connection-prevent-flooding).
P.S: I added "-1" in `login_response` to maintain compatibility with "old `login_response` versions"

### CODE REVIEW

**Comment by JTF4** [comment]
I could break into this much faster without brute force. 

Since the entire thing is running with a non https socket you could easily sniff out the password during the username and password exchange. 

But I do like the rate limiting.

**Review by hrueger — CHANGES_REQUESTED** [review]
Cool.
>P.S: I added "-1" in login_response to maintain compatibility with "old login_response versions"

Just wondering: compatibility with what? 

I personally would like to see the error message generated on the server side. That way we could implement more errors (like from a user access control with specific rights for specific users).
What do you think?

**Comment by MatteoGheza** [comment]
@hrueger sorry for the late response

> Cool.
> 
> > P.S: I added "-1" in login_response to maintain compatibility with "old login_response versions"
> 
> Just wondering: compatibility with what?

I meant compatibility with older versions of the UI.
If we change "login_response" response from boolean to an object (for example,  
`{ "status":"success", "message":"" }`  
`{ "status":"error", "message":"Wrong username or password!" }`  
`{ "status":"error", "message":"Too many attemps! Please retry later." }`  
) the old version of `auth.service.ts` stops working. 

> I personally would like to see the error message generated on the server side. That way we could implement more errors (like from a user access control with specific rights for specific users).

So do I.

> What do you think?

Using server-side generated error messages, we could also transmit to the client the number of attempts left and how long it has to wait before a new attemp.
I think we can use a new websocket event, for example `login_response`, so the server can emit both `login_result` with the old "boolean" response and the new `login_response` with an object.

**Comment by hrueger** [comment]
>sorry for the late response
No problem.

> meant compatibility with older versions of the UI.
I might be wrong, but why would we need that? The only clients having that UI are the browser clients and when you refresh them, the latest UI is being fetched, or is it not?

**Comment by hrueger** [comment]
Or do you mean caching from the service worker? That could indeed be a problem. However, I'm not a fan of legacy code ;-) My suggestion would be to display a changelog message on every first start of a new version. We could save the current version in the config file and once it does not match anymore (because TA was updated), we show the changelog.
In there we could inform the user to refresh the browser to get the latest UI.

**Comment by MatteoGheza** [comment]
> I might be wrong, but why would we need that? The only clients having that UI are the browser clients and when you refresh them, the latest UI is being fetched, or is it not?

I meant that probably some people who are using Tally Arbiter from source don't always remember to re-compile the UI when they pull from Git

**Comment by MatteoGheza** [comment]
> However, I'm not a fan of legacy code ;-)

I think we can "deprecate" login_result with boolean in the next "big release"

**Comment by hrueger** [comment]
Ok, I agree

**Comment by hrueger** [comment]
>I meant that probably some people who are using Tally Arbiter from source don't always remember to re-compile the UI when they pull from Git.
We could add a proxy for `localhost:4200` so that when TallyArbiter is started in dev mode (NODE_ENV=production) not the bundled UI is served but instead `localhost:4200`.

**Comment by MatteoGheza** [comment]
I think that now login rate limits are working as requested

**Pull request merged**
