### PR TITLE
Migrate logging and tally data to Winston

### PR DESCRIPTION
**Pull request by MatteoGheza**
As described in #195 
Everything is compatible with the old version of the logger, except that now every line of server logs is similar to
```[2021-08-31 21:53:19] info: Starting HTTP Server.``` or ```[2021-08-31 21:53:40] error: An error occurred etc```

-------------

_Winston options for file output:_
chrome_BNcSWGT34T

Current options used in server loggin and in Tally data:
```javascript
{
  filename: filepath,
  maxsize: 3e+7
  maxFiles: 3,
  ...
}
```

-------------

@JTF4 can you explain to me what is Tally data logging and why its format is
`{TallyObj},  {TallyObj}, {TallyObj},`?

### CODE REVIEW

**Comment by JTF4** [comment]
@MatteoGheza the tally data logging is there so that we can enable edit decision list exporting in the future.

**Comment by MatteoGheza** [comment]
> @MatteoGheza the tally data logging is there so that we can enable edit decision list exporting in the future.

@JTF4 can we change the format into
```javascript
[
  {TallyObj},
  {TallyObj},
  {TallyObj}
]
```
or into
```javascript
[
  { timestamp: current_timestamp, tally: {TallyObj} },
  { timestamp: current_timestamp, tally: {TallyObj} },
  { timestamp: current_timestamp, tally: {TallyObj} },
]
```

**Comment by josephdadams** [comment]
I see no reason why we can't make that change. If we come up with an EDL feature in the future, I have some specific thoughts on how I would want to see it handled anyway, so it's fine with me to make changes to how it's currently logged to a file.

**Comment by JTF4** [comment]
The latter should work. As long as the tally data object has the device name in it with the tally1-4 it will work. In the future I'll also add a time code to the log object so it can sync with a recorder like a ki pro.

**Comment by MatteoGheza** [comment]
In future, when we start working on EDL and similar features, I think I can replace Winston with a custom function for storing Tally data in a better method then the one used now or then the method used before this PR.

**Comment by josephdadams** [comment]
Sounds good. I shall open a new issue sometime to describe what I was thinking for EDL.

**Comment by MatteoGheza** [comment]
@josephdadams @JTF4 is this ready? Do I have to revert edits to Tally Data logger?

**Comment by josephdadams** [comment]
If it works (I haven’t had time to test), it’s fine with me to merge. W

**Pull request merged**
